# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
tensor2 = torch.rand(7,7)
tensor2, tensor2.shape

(tensor([[0.4084, 0.6401, 0.5918, 0.6038, 0.2131, 0.6165, 0.5639],
         [0.7786, 0.2413, 0.3624, 0.5145, 0.4824, 0.2313, 0.9715],
         [0.4719, 0.9341, 0.5698, 0.6819, 0.1363, 0.3937, 0.1929],
         [0.4162, 0.2552, 0.4274, 0.8429, 0.9620, 0.0229, 0.1676],
         [0.2831, 0.5807, 0.9341, 0.6535, 0.4150, 0.9307, 0.0840],
         [0.0852, 0.8907, 0.2512, 0.4888, 0.4101, 0.1893, 0.4531],
         [0.9599, 0.9882, 0.4083, 0.9172, 0.6293, 0.1573, 0.6836]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [9]:
print(f"tensor2:{tensor2}")
# Create another random tensor
tensor3 = torch.rand(1,7)
print(f"tensor3:{tensor3}")
# Perform matrix multiplication
matrix_mul = torch.matmul(tensor2, tensor3.T)
print(f"matrix_mul:{matrix_mul}")

tensor2:tensor([[0.8434, 0.2172, 0.6182, 0.2788, 0.6283, 0.2555, 0.6996],
        [0.7704, 0.3011, 0.4666, 0.9489, 0.6856, 0.5487, 0.8057],
        [0.9529, 0.7436, 0.2338, 0.4451, 0.9630, 0.4685, 0.1759],
        [0.0247, 0.2474, 0.8910, 0.3421, 0.3034, 0.2641, 0.6814],
        [0.3265, 0.4819, 0.1617, 0.0757, 0.1475, 0.5742, 0.1772],
        [0.4354, 0.7764, 0.1497, 0.0230, 0.1212, 0.2290, 0.2352],
        [0.6083, 0.8933, 0.9666, 0.8106, 0.4626, 0.3499, 0.3362]])
tensor3:tensor([[0.8490, 0.8895, 0.5673, 0.0488, 0.4677, 0.9124, 0.3139]])
matrix_mul:tensor([[2.0201],
        [2.3070],
        [2.5579],
        [1.3599],
        [1.4497],
        [1.4858],
        [2.5400]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [22]:
# Set manual seed
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
# Create two random tensors

tensor_2 = torch.rand(7,7)
tensor_3 = torch.rand(1,7)

# Matrix multiply tensors
Matrix_Mul = torch.matmul(tensor_2, tensor_3.T)
Matrix_Mul, Matrix_Mul.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [6]:
# Set random seed on the GPU
RANDOM_SEED = 1234
torch.cuda.manual_seed(RANDOM_SEED)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [10]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
torch.cuda.is_available()
device = "cuda" if torch.cuda.is_available() else "cpu"
device

# Create two random tensors on GPU
tensor_A = torch.rand(2, 3).to(device)
tensor_B = torch.rand(2, 3).to(device)
tensor_A, tensor_B

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [12]:
# Perform matmul on tensor_A and tensor_B
matmul = torch.matmul(tensor_A, tensor_B.T)
matmul, matmul.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [15]:
# Find max
max = torch.max(matmul)
print(f"max:{max}")
# Find min
min = torch.min(matmul)
print(f"min:{min}")

max:0.5617256760597229
min:0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [16]:
# Find arg max
max_arg = torch.argmax(matmul)
print(f"index of max:{max_arg}")
# Find arg min
min_arg = torch.argmin(matmul)
print(f"index of min:{min_arg}")

index of max:3
index of min:0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [18]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor = torch.rand(1, 1, 1, 10)

# Remove single dimensions
tensor_remove = tensor.squeeze()

# Print out tensors and their shapes
tensor, tensor.shape, tensor_remove, tensor_remove.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))